export const ADD_TOAST_MESSAGE = 'ADD_TOAST_MESSAGE';
export const DELETE_TOAST_MESSAGE = 'DELETE_TOAST_MESSAGE';
export const DELETE_ALL_TOASTS = 'DELETE_ALL_TOASTS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
